### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by kubik1984** [Zerto-Tech-Marketing/Bulk-VPG-Re-IP-Edit#2]
Any chance you could update this script, since 7.0 its been spitting out the following errors... Thanks!

   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Invoke-RestMethod : Failed parsing 'accbf2c1-bccf-4231-adb7-b625a2e4eb14.vm-971' as a valid VPG Settings identifier.
At C:\Users\rkubik\Desktop\Zerto Scripts\test.ps1:183 char:21
+ ... ttingNICs = Invoke-RestMethod -Method Get -Uri $GetVMSettingNICsURL - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by wcarroll** [comment]
Hi @kubik1984, this error was a bug with the Zerto Virtual Manager API. This issue has since been fixed and should no longer happen on an updated version of Zerto.
